export const colors = {
  darkPurple: "#6C42FF",
  purple: "#BCB1FF",
  lightBlue: "#469ED4",
  aqua: "#34cbbf",
  border: "rgba(74,72,132, 0.5)",
  blueSemiTransparent: "#171534",
  white: "#FDFCFE",
  darkBlue: "#33325b",
  blue: "#1542b4",
  dark: "#07001c",
  black: "#05011b",
  inputText: "#BEC4D2",
  error: "#FF6B6B",
};

export const FONTS = {
  MerriweatherLightIt: "Merriweather-LightIt",
  MerriweatherLight: "Merriweather Light",
  MerriweatherRegular: "Merriweather-Regular",
  MerriweatherItalic: "Merriweather-Italic",
  MerriweatherBold: "Merriweather-Bold",
  MerriweatherBoldIt: "Merriweather-BoldIt",
  MerriweatherUltraBold: "Merriweather UltraBold",
  MerriweatherUltraBdIt: "Merriweather-UltraBdIt",
  //RedditSans
  RedditSansBlack: "RedditSans-Black",
  RedditSansBlackItalic: "RedditSans-BlackItalic",
  RedditSansBold: "RedditSans-Bold",
  RedditSansBoldItalic: "RedditSans-BoldItalic",
  RedditSansExtraBold: "RedditSans-ExtraBold",
  RedditSansExtraLight: "RedditSans-ExtraLight",
  RedditSansExtraLightItalic: "RedditSans-ExtraLightItalic",
  RedditSansItalic: "RedditSans-Italic",
  RedditSansLight: "RedditSans-Light",
  RedditSansLightItalic: "RedditSans-LightItalic",
  RedditSansMedium: "RedditSans-Medium",
  RedditSansMediumItalic: "RedditSans-MediumItalic",
  RedditSansRegular: "RedditSans-Regular",
  RedditSansSemiBold: "RedditSans-SemiBold",
  RedditSansSemiBoldItalic: "RedditSans-SemiBoldItalic",
};
